# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Ecstatic'), (5, 'Passionate'), (10, 'Happy'), (15, 'Optimistic'), (20, 'Content'), (25, 'Board'), (26, 'Tired'), (27, 'Hungry'), (30, 'Pessimistic'), (35, 'Frustrated'), (40, 'Overwhelmed'), (45, 'Worried'), (50, 'Angry'), (55, 'Jealous'), (60, 'Insecure'), (65, 'Guilty'), (70, 'Fear'), (75, 'Grief'), (80, 'Despair'), (85, 'Paranoid')]),
        ),
    ]
