# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-09 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20190828_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['-recorded_at']},
        ),
    ]
